# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
#  - 3.5

env:
  - ELASTIC_VERSION=7.4.0 ELASTIC_PASSWORD=my_elastic_password12390

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

services:
  - docker

before_install:
  - docker network create nlp_network
  - docker run --rm -itd --net=nlp_network -e ELASTIC_PASSWORD=$ELASTIC_PASSWORD -e discovery.type=single-node -e cluster.name=docker-cluster -e bootstrap.memory_lock=true -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -p 9200:9200 --name nlp_elastic docker.elastic.co/elasticsearch/elasticsearch-oss:$ELASTIC_VERSION
  - docker run --rm -itd --net=nlp_network -e SERVER_NAME=kibana -e ELASTICSEARCH_URL=http://nlp_elastic:9200 -e ELASTICSEARCH_HOSTS=http://nlp_elastic:9200 -p 5601:5601 --name nlp_kibana docker.elastic.co/kibana/kibana-oss:$ELASTIC_VERSION
  - pip install codecov

#after_success:
#  - codecov # submit coverage

deploy:
  provider: pypi
  distributions: sdist
  user: "__token__"
  password:
    secure: oVJoNGkEEJVg/yiR2vAO9EPv64Jo4aB9Ovq//GVIOI0VtnMehm3rsRc0uC491/7PjJJl4m9FOMfRZfZOXCovUW9CizhsCToOOPgmO/Dy3MmYn8njsAw9skawAkNm7kGBy8h6zzxgM/VhWaGbByNywiUsiKJRgCAbgoUe3K+pH5tSxUjJ6Cwjo+i0Ck2Kl6pN0p4tppOgswIn+qjgr7568LdzlpAXZq+kAPJdwgJtWJgNJJ1EHlHMRRzYNduye+DUopvD3nH2jNYkyO7cr9TmvuTKHIXByrcXP8Z3cBr/HRFREUvgE3RrLVjVkTF82o3jbwJ0HfqTOwa8vKIHhTuX0oo2A3BuLkbeTW9Uwmfzo+IgsuHuZP3Lh+WTjzdAtzioVA+KfvYTy8zIiJMH0GjP2gjPlhdWk+joQhcozChN9AJRuBln2biKNw+mtvC3PHzpc3Cnb1ksKLVS7+S1M39gMydIffcmrQGL86oWeFNzfDb74inYFjthfHcbZEHIzDZlxcR/KxIztYR1lD3L3/fesVvSUAxz7nODcms3nW2CJLRAIPC1aEH8UxJn8Y4yLP6z+3RCk0IF5r3tnmpUy2AW9gwf8E2HyaJqGGZrMTqUpDD6qwhlv7WQL8+UBpVux2t5BGen2cI3HIX7NIX46L5GBjR6qWHVNJIwGrUO+O58N8M=
  on:
    tags: true
    python: 3.7
    skip_existing: true
